import type { Metadata } from "next";
import "../assets/css/globals.css";
import DesktopHeader from "@/components/common/desktopHeader";
import Footer from "@/components/common/footer";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className="flex flex-col">
        <Toaster position="top-right" />
        <DesktopHeader></DesktopHeader>
        {children}
        <Footer></Footer>
      </body>
    </html>
  );
}
