import About from "@/components/common/about";
import Greetings from "@/components/common/greetings";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "محمد امین درخشنده",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main>
      <div className="homepage-container flex flex-col gap-10">
        <Greetings></Greetings>
        <About></About>
      </div>
    </main>
  );
}
